name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  prepare:
    name: Dokcer tag
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.docker-tag.outputs.tag }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Docker Image Name
        id: docker-tag
        run: |
          # Extract the version from Cargo.toml
          VERSION=$(grep '^version' Cargo.toml | head -n1 | sed 's/version = "\(.*\)"/\1/')
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

  build:
    name: Build Docker Images
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.proverproxy.ubuntu
          push: true
          tags: kromanetwork/zkvm-prover-proxy:${{ needs.prepare.outputs.docker-tag }}
